STATIC_PATH = "static"
DEBUG = true
DB_FILE = "app.db"
JWT_TOKEN_LOCATION = ["cookies"]
JWT_ACCESS_COOKIE_NAME = "lemuria_token_access"
JWT_ACCESS_COOKIE_PATH = "/api/v1/"
JWT_ACCESS_CSRF_COOKIE_NAME = "lemuria_csrf_access"
JWT_ACCESS_CSRF_COOKIE_PATH = "/"
JWT_REFRESH_COOKIE_NAME = "lemuria_token_renew"
JWT_REFRESH_COOKIE_PATH = "/api/v1/auth/renew"
JWT_REFRESH_CSRF_COOKIE_NAME = "lemuria_csrf_renew"
JWT_REFRESH_CSRF_COOKIE_PATH = "/"
JWT_COOKIE_CSRF_PROTECT = true
JWT_COOKIE_SECURE = false
JWT_COOKIE_SAMESITE = "Strict"
JWT_SECRET_KEY = "**changeme**"
SECRET_KEY = "**changeme**"
POSITION_UPDATE_TICK = 0.2